from alembic import op
import sqlalchemy as sa
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(255), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")))
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table("categories", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False, unique=True), sa.Column("type", sa.String(20), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")))
    op.create_table("transactions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("category_id", sa.Integer(), sa.ForeignKey("categories.id")), sa.Column("tx_date", sa.Date(), nullable=False), sa.Column("description", sa.String(255), nullable=False), sa.Column("amount", sa.Numeric(12,2), nullable=False), sa.Column("type", sa.String(20), nullable=False), sa.Column("note", sa.Text()), sa.Column("source", sa.String(50), nullable=False), sa.Column("imported", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")))
    op.create_table("rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("text", sa.String(255), nullable=False), sa.Column("category_name", sa.String(120), nullable=False), sa.Column("tx_type", sa.String(20), nullable=False), sa.Column("priority", sa.Integer(), nullable=False, server_default="50"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")))
    op.create_table("budgets", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("month", sa.String(7), nullable=False), sa.Column("goal_savings", sa.Numeric(12,2), nullable=False, server_default="0"), sa.Column("monthly_limit", sa.Numeric(12,2), nullable=False, server_default="0"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")))
    op.create_table("budget_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("budget_id", sa.Integer(), sa.ForeignKey("budgets.id"), nullable=False), sa.Column("category_name", sa.String(120), nullable=False), sa.Column("amount", sa.Numeric(12,2), nullable=False, server_default="0"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")))
    op.create_table("reminders", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("text", sa.String(255), nullable=False), sa.Column("reminder_date", sa.Date(), nullable=False), sa.Column("repeat", sa.String(20), nullable=False, server_default="none"), sa.Column("priority", sa.Integer(), nullable=False, server_default="3"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")))
    op.create_table("audit_log", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("action", sa.String(80), nullable=False), sa.Column("detail", sa.String(500), nullable=False), sa.Column("entity_type", sa.String(80)), sa.Column("entity_id", sa.Integer()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")))
    op.create_table("imports", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("filename", sa.String(255), nullable=False), sa.Column("rows_total", sa.Integer(), nullable=False, server_default="0"), sa.Column("rows_inserted", sa.Integer(), nullable=False, server_default="0"), sa.Column("rows_skipped", sa.Integer(), nullable=False, server_default="0"), sa.Column("hash", sa.String(128), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")))

def downgrade():
    op.drop_table("imports"); op.drop_table("audit_log"); op.drop_table("reminders"); op.drop_table("budget_items"); op.drop_table("budgets"); op.drop_table("rules"); op.drop_table("transactions"); op.drop_table("categories"); op.drop_table("users")
